// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations.OrderDB
{
    [DbContext(typeof(OrderDBContext))]
    partial class OrderDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Common.Models.OrderModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastOrderUpdate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderTimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentDetailsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShippingDetailsId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Common.Models.SKU", b =>
                {
                    b.Property<int>("SKUId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderModelID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SKUCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SKUId");

                    b.HasIndex("OrderModelID");

                    b.ToTable("SKU");
                });

            modelBuilder.Entity("Common.Models.SKU", b =>
                {
                    b.HasOne("Common.Models.OrderModel", null)
                        .WithMany("SKU")
                        .HasForeignKey("OrderModelID");
                });

            modelBuilder.Entity("Common.Models.OrderModel", b =>
                {
                    b.Navigation("SKU");
                });
#pragma warning restore 612, 618
        }
    }
}
